### ISSUE TITLE
Consider an alternative License since this package is 'infrastructural'

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-react-chart-library#1]
Whereas with the dGC API Server we used GNU AGPL because we wanted to ensure copyleft rights were protected and passed on to users, even if someone was running the code as a web service, in this case of the react library, I wonder if we should use a more permissive license that does not prevent someone using the library in, for example, a proprietary app.

Suggestion would be probably MIT license which is very permissive and has no 'viral' license (I hate that term) properties or copyleft. It's just a 'do what you want with this code' license.

One to consider

**Comment by eatyourpeas** [comment]
changed to MIT
